/**
 * The 12 BVAL seeds, transcribed from tests/fixtures/seeds/registry-seed.json (verified 2026-10-02;
 * checked field by field by tests/registry-seeds.test.ts). Membership: the CCS 2026-27 league
 * alignment and bval.org/field-hockey. The BVAL docx grid code 'WG' lives in
 * LEAGUES bval.officialCodes, never in aliases.
 */

import type { Seed } from './seed';

export const BVAL_SEEDS: readonly Seed[] = [
  // ----- Mt. Hamilton (6) -----
  {
    id: 'c81780c9-d396-45a1-a7f9-0aae05905a97',
    slug: 'branham',
    name: 'Branham',
    shortName: 'Branham',
    abbr: 'BR',
    acronym: 'BHS',
    mascot: 'Bruins',
    city: 'San Jose',
    section: 'ccs',
    league: 'bval',
    division: 'mt-hamilton',
    dataCoverage: 'full',
    colors: ['022C66', '046DFF'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/san-jose/branham-bruins/field-hockey/',
    aliases: [
      'Branham', 'BRANHAM', 'Branham Bruins', 'Branham High School',
    ],
    sbliveTeamId: '458510',
    sbliveSlug: '458510-branham-bruins',
  },
  {
    id: '773e862d-e186-44aa-b268-461b4064ce52',
    slug: 'christopher',
    name: 'Christopher',
    shortName: 'Christopher',
    abbr: 'CH',
    acronym: 'CHS',
    mascot: 'Cougars',
    city: 'Gilroy',
    section: 'ccs',
    league: 'bval',
    division: 'mt-hamilton',
    dataCoverage: 'full',
    colors: ['222222', 'C8880A'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/gilroy/christopher-cougars/field-hockey/',
    aliases: [
      'Christopher', 'CHRISTOPHER', 'Christopher Cougars', 'Christopher High School',
      'Christopher (Gilroy)',
    ],
    sbliveTeamId: '458687',
    sbliveSlug: '458687-christopher-cougars',
  },
  {
    id: 'fa72c6cc-34dc-4bb4-a184-9c4efaa643d3',
    slug: 'gilroy',
    name: 'Gilroy',
    shortName: 'Gilroy',
    abbr: 'GI',
    acronym: 'GHS',
    mascot: 'Mustangs',
    city: 'Gilroy',
    section: 'ccs',
    league: 'bval',
    division: 'mt-hamilton',
    dataCoverage: 'full',
    colors: ['034CB2', 'FFFFFF'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/gilroy/gilroy-mustangs/field-hockey/',
    aliases: [
      'Gilroy', 'GILROY', 'Gilroy Mustangs', 'Gilroy High School',
    ],
    sbliveTeamId: '458690',
    sbliveSlug: '458690-gilroy-mustangs',
  },
  {
    id: 'bd6662e8-a2ee-45ca-b0e8-dd03dec005c9',
    slug: 'leigh',
    name: 'Leigh',
    shortName: 'Leigh',
    abbr: 'LE',
    acronym: 'LHS',
    mascot: 'Longhorns',
    city: 'San Jose',
    section: 'ccs',
    league: 'bval',
    division: 'mt-hamilton',
    dataCoverage: 'full',
    colors: ['00824B', 'C8880A'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/san-jose/leigh-longhorns/field-hockey/',
    aliases: [
      'Leigh', 'LEIGH', 'Leigh Longhorns', 'Leigh High School',
    ],
    sbliveTeamId: '458515',
    sbliveSlug: '458515-leigh-longhorns',
  },
  {
    id: 'cb6e2cbf-71b1-4ef0-9c63-feef33010bf2',
    slug: 'leland',
    name: 'Leland',
    shortName: 'Leland',
    abbr: 'LD',
    acronym: 'LHS',
    mascot: 'Chargers',
    city: 'San Jose',
    section: 'ccs',
    league: 'bval',
    division: 'mt-hamilton',
    dataCoverage: 'full',
    colors: ['046DFF', 'C8880A'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/san-jose/leland-chargers/field-hockey/',
    aliases: [
      'Leland', 'LELAND', 'Leland Chargers', 'Leland High School',
    ],
    sbliveTeamId: '459053',
    sbliveSlug: '459053-leland-chargers',
  },
  {
    id: 'e0d5f596-a80c-4142-9c2a-e2bee576fdc9',
    slug: 'willow-glen',
    name: 'Willow Glen',
    shortName: 'Willow Glen',
    abbr: 'WG',
    acronym: 'WGHS',
    mascot: 'Rams',
    city: 'San Jose',
    section: 'ccs',
    league: 'bval',
    division: 'mt-hamilton',
    dataCoverage: 'full',
    colors: ['CC0022', 'C8880A'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/san-jose/willow-glen-rams/field-hockey/',
    aliases: [
      'Willow Glen', 'WILLOW GLEN', 'Willow Glen Rams', 'Willow Glen High School',
    ],
    sbliveTeamId: '459057',
    sbliveSlug: '459057-willow-glen-rams',
  },

  // ----- Santa Teresa (6; MaxPreps’ table omits Prospect) -----
  {
    id: '8c56113f-9229-43a2-a56e-4f8443494857',
    slug: 'del-mar',
    name: 'Del Mar',
    shortName: 'Del Mar',
    abbr: 'DM',
    acronym: 'DMHS',
    mascot: 'Dons',
    city: 'San Jose',
    section: 'ccs',
    league: 'bval',
    division: 'santa-teresa',
    dataCoverage: 'full',
    colors: ['222222', 'C8880A'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/san-jose/del-mar-dons/field-hockey/',
    aliases: [
      'Del Mar', 'DEL MAR', 'Del Mar Dons', 'Del Mar High School', 'Del Mar (San Jose)',
    ],
    sbliveTeamId: '458513',
    sbliveSlug: '458513-del-mar-dons',
  },
  {
    id: 'a52c60ac-fbe9-438f-b052-c1eba43afacd',
    slug: 'live-oak',
    name: 'Live Oak',
    shortName: 'Live Oak',
    abbr: 'LO',
    acronym: 'LOHS',
    mascot: 'Acorns',
    city: 'Morgan Hill',
    section: 'ccs',
    league: 'bval',
    division: 'santa-teresa',
    dataCoverage: 'full',
    colors: ['00824B', 'C8880A'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/morgan-hill/live-oak-acorns/field-hockey/',
    aliases: [
      'Live Oak', 'LIVE OAK', 'Live Oak Acorns', 'Live Oak High School', 'Live Oak (Morgan Hill)',
    ],
    sbliveTeamId: '458848',
    sbliveSlug: '458848-live-oak-acorns',
  },
  {
    id: '24d74484-a18f-450e-9f4a-ccbd5299bf1f',
    slug: 'prospect',
    name: 'Prospect',
    shortName: 'Prospect',
    abbr: 'PS',
    acronym: 'PHS',
    mascot: 'Panthers',
    city: 'Saratoga',
    section: 'ccs',
    league: 'bval',
    division: 'santa-teresa',
    dataCoverage: 'full',
    colors: ['034CB2', 'C8880A'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/saratoga/prospect-panthers/field-hockey/',
    aliases: [
      'Prospect', 'PROSPECT', 'Prospect Panthers', 'Prospect High School', 'Prospect (Saratoga)',
    ],
    sbliveTeamId: '458517',
    sbliveSlug: '458517-prospect-panthers',
  },
  {
    id: '30d65e43-1478-45b5-90de-fd69689344f8',
    slug: 'silver-creek',
    name: 'Silver Creek',
    shortName: 'Silver Creek',
    abbr: 'SK',
    acronym: 'SCHS',
    mascot: 'Raiders',
    city: 'San Jose',
    section: 'ccs',
    league: 'bval',
    division: 'santa-teresa',
    dataCoverage: 'full',
    colors: ['CC4E10', '222222'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/san-jose/silver-creek-raiders/field-hockey/',
    aliases: [
      'Silver Creek', 'SILVER CREEK', 'Silver Creek Raiders', 'Silver Creek High School',
    ],
    sbliveTeamId: '547018',
    sbliveSlug: '547018-silver-creek-raiders',
  },
  {
    id: '01bf9fda-9b10-4f04-9eef-3195d7d501dc',
    slug: 'sobrato',
    name: 'Ann Sobrato',
    shortName: 'Ann Sobrato',
    abbr: 'SO',
    acronym: 'ASHS',
    mascot: 'Bulldogs',
    city: 'Morgan Hill',
    section: 'ccs',
    league: 'bval',
    division: 'santa-teresa',
    dataCoverage: 'full',
    colors: ['8F0018', '222222'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/morgan-hill/ann-sobrato-bulldogs/field-hockey/',
    aliases: [
      'Ann Sobrato', 'Sobrato', 'SOBRATO', 'ANN SOBRATO', 'Ann Sobrato Bulldogs',
      'Sobrato Bulldogs', 'Ann Sobrato High School', 'Sobrato High School',
    ],
    sbliveTeamId: '458846',
    sbliveSlug: '458846-ann-sobrato-bulldogs',
  },
  {
    id: '1959d651-408f-4764-94a5-144cea89c499',
    slug: 'westmont',
    name: 'Westmont',
    shortName: 'Westmont',
    abbr: 'WM',
    acronym: 'WHS',
    mascot: 'Warriors',
    city: 'Campbell',
    section: 'ccs',
    league: 'bval',
    division: 'santa-teresa',
    dataCoverage: 'full',
    colors: ['222222', 'CC0022'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/campbell/westmont-warriors/field-hockey/',
    aliases: [
      'Westmont', 'WESTMONT', 'Westmont Warriors', 'Westmont High School', 'Westmont (Campbell)',
    ],
    sbliveTeamId: '458520',
    sbliveSlug: '458520-westmont-warriors',
  },
];
