/**
 * The 6 EAL seeds (Northern Section's Eastern Athletic League), transcribed from
 * tests/fixtures/seeds/registry-seed-ns.json (verified 2026-10-04; checked field by field by
 * tests/registry-seeds.test.ts). Seed order is alphabetical. Davis and Bella Vista are Sac-Joaquin
 * Section schools; Red Bluff is not fielding a varsity team in 2026 (LEAGUES eal.withdrawnNames,
 * maxprepsExtraRows). Mascot and city come from MaxPreps' team-context payload, not from standings.
 */

import type { Seed } from './seed';

export const EAL_SEEDS: readonly Seed[] = [
  // ----- EAL (6) -----
  {
    id: '204d6632-16ce-41fc-a733-dd11ec3af582',
    slug: 'bella-vista',
    name: 'Bella Vista',
    shortName: 'Bella Vista',
    abbr: 'BV',
    acronym: 'BVHS',
    mascot: 'Broncos',
    city: 'Fair Oaks',
    section: 'ns',
    league: 'eal',
    division: 'eal',
    dataCoverage: 'full',
    colors: ['CC0022', 'FFFFFF'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/fair-oaks/bella-vista-broncos/field-hockey/',
    aliases: [
      'Bella Vista', 'BELLA VISTA', 'Bella Vista High School', 'Bella Vista Broncos', 'Bella Vista (Fair Oaks)',
    ],
    sbliveTeamId: '459060',
    sbliveSlug: '459060-bella-vista-broncos',
    sbliveSchoolId: '12991',
  },
  {
    id: '041ef7b7-089b-4e7d-9c9c-9ff1f833f829',
    slug: 'chico',
    name: 'Chico',
    shortName: 'Chico',
    abbr: 'CI',
    acronym: 'CHS',
    mascot: 'Panthers',
    city: 'Chico',
    section: 'ns',
    league: 'eal',
    division: 'eal',
    dataCoverage: 'full',
    colors: ['CC0022', 'C8880A'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/chico/chico-panthers/field-hockey/',
    aliases: [
      'Chico', 'CHICO', 'Chico High', 'Chico High School', 'Chico Panthers',
    ],
    sbliveTeamId: '458564',
    sbliveSlug: '458564-chico-panthers',
    sbliveSchoolId: '10335',
  },
  {
    id: '8f1a8024-2d40-4cab-bcba-3b9b367c6873',
    slug: 'corning',
    name: 'Corning',
    shortName: 'Corning',
    abbr: 'CR',
    acronym: 'CHS',
    mascot: 'Cardinals',
    city: 'Corning',
    section: 'ns',
    league: 'eal',
    division: 'eal',
    dataCoverage: 'full',
    colors: ['CC0022', '222222'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/corning/corning-cardinals/field-hockey/',
    aliases: [
      'Corning', 'CORNING', 'Corning High School', 'Corning Cardinals',
    ],
    sbliveTeamId: '458585',
    sbliveSlug: '458585-corning-cardinals',
    sbliveSchoolId: '10501',
  },
  {
    id: '288ca10d-8448-41e9-b26e-463df226b8c8',
    slug: 'davis',
    name: 'Davis',
    shortName: 'Davis',
    abbr: 'DV',
    acronym: 'DSHS',
    mascot: 'Blue Devils',
    city: 'Davis',
    section: 'ns',
    league: 'eal',
    division: 'eal',
    dataCoverage: 'full',
    colors: ['034CB2', 'FFFFFF'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/davis/davis-sr-blue-devils/field-hockey/',
    aliases: [
      'Davis', 'DAVIS', 'Davis Sr.', 'Davis Sr', 'Davis Senior',
      'Davis Senior High School', 'Davis High', 'Davis High School', 'Davis Blue Devils', 'Davis Sr. Blue Devils',
      'Davis Sr. (Davis)',
    ],
    sbliveTeamId: '458605',
    sbliveSlug: '458605-davis-blue-devils',
    sbliveSchoolId: '10575',
  },
  {
    id: 'b4268b1c-b3df-4dd5-b52c-5355d8a48e42',
    slug: 'lassen',
    name: 'Lassen',
    shortName: 'Lassen',
    abbr: 'LS',
    acronym: 'LHS',
    mascot: 'Grizzlies',
    city: 'Susanville',
    section: 'ns',
    league: 'eal',
    division: 'eal',
    dataCoverage: 'full',
    colors: ['754ACC', 'C8880A'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/susanville/lassen-grizzlies/field-hockey/',
    aliases: [
      'Lassen', 'LASSEN', 'Lassen High School', 'Lassen Grizzlies', 'Lassen (Susanville)',
    ],
    sbliveTeamId: '458783',
    sbliveSlug: '458783-lassen-grizzlies',
    sbliveSchoolId: '11554',
  },
  {
    id: '8e01c2fa-4888-483f-8d26-6a45518c1bd8',
    slug: 'pleasant-valley',
    name: 'Pleasant Valley',
    shortName: 'Pleasant Val.',
    abbr: 'PV',
    acronym: 'PVHS',
    mascot: 'Vikings',
    city: 'Chico',
    section: 'ns',
    league: 'eal',
    division: 'eal',
    dataCoverage: 'full',
    colors: ['022C66', 'FFFFFF'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/chico/pleasant-valley-vikings/field-hockey/',
    aliases: [
      'Pleasant Valley', 'PLEASANT VALLEY', 'Pleasant Valley High School', 'Pleasant Valley Vikings', 'Pleasant Valley (Chico)',
    ],
    sbliveTeamId: '458566',
    sbliveSlug: '458566-pleasant-valley-vikings',
    // si.com school id from the page props' school.id: Pleasant Valley's si.com logo is a team image.
    sbliveSchoolId: '10337',
  },
];
