/**
 * The 9 MCAL seeds (North Coast Section), transcribed from tests/fixtures/seeds/registry-seed-ncs.json
 * (verified 2026-10-02; checked field by field by tests/registry-seeds.test.ts). Seed order is the
 * MCAL spring draw order (AW 1 … MA 9). The schedule-PDF codes live in LEAGUES mcal.officialCodes;
 * University (San Francisco) carries no bare "University" alias, which is ambiguous statewide.
 */

import type { Seed } from './seed';

export const MCAL_SEEDS: readonly Seed[] = [
  // ----- Marin County (9) -----
  {
    id: '5cbb07ea-6b9c-4286-81f6-2708253e1add',
    slug: 'archie-williams',
    name: 'Archie Williams',
    shortName: 'Archie Williams',
    abbr: 'AW',
    acronym: 'AWHS',
    mascot: 'Peregrine Falcons',
    city: 'San Anselmo',
    section: 'ncs',
    league: 'mcal',
    division: 'marin-county',
    dataCoverage: 'full',
    colors: ['00824B', 'FFFFFF'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/san-anselmo/archie-williams-peregrine-falcons/field-hockey/',
    aliases: [
      'Archie Williams', 'ARCHIE WILLIAMS', 'Archie Williams High School',
      'Archie Williams Peregrine Falcons', 'Archie Williams Falcons',
      'Archie Williams (San Anselmo)', 'Sir Francis Drake High School',
    ],
    sbliveTeamId: '487100',
    sbliveSlug: '487100-archie-williams-falcons',
  },
  {
    id: '12616b84-157c-48d3-b353-434576d9df8d',
    slug: 'redwood',
    name: 'Redwood',
    shortName: 'Redwood',
    abbr: 'RW',
    acronym: 'RHS',
    mascot: 'Giants',
    city: 'Larkspur',
    section: 'ncs',
    league: 'mcal',
    division: 'marin-county',
    dataCoverage: 'full',
    colors: ['CC0022', '454444'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/larkspur/redwood-giants/field-hockey/',
    aliases: [
      'Redwood', 'REDWOOD', 'Redwood High School', 'Redwood Giants', 'Redwood (Larkspur)',
    ],
    sbliveTeamId: '459143',
    sbliveSlug: '459143-redwood-giants',
  },
  {
    id: '7298608f-2310-4399-aa07-d6bc50df3f4e',
    slug: 'tamalpais',
    name: 'Tamalpais',
    shortName: 'Tamalpais',
    abbr: 'TM',
    acronym: 'THS',
    mascot: 'Red-Tailed Hawks',
    city: 'Mill Valley',
    section: 'ncs',
    league: 'mcal',
    division: 'marin-county',
    dataCoverage: 'full',
    colors: ['022C66', 'CC0022'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/mill-valley/tamalpais-red-tailed-hawks/field-hockey/',
    aliases: [
      'Tamalpais', 'TAMALPAIS', 'Tam', 'Tamalpais High School', 'Tamalpais Red-Tailed Hawks',
      'Tamalpais (Mill Valley)',
    ],
    sbliveTeamId: '486964',
    sbliveSlug: '486964-tamalpais-red-tailed-hawks',
    sbliveSchoolId: '13445',
  },
  {
    id: '6c68b5d2-1cab-449d-9140-bd7c8adb2791',
    slug: 'berkeley',
    name: 'Berkeley',
    shortName: 'Berkeley',
    abbr: 'BK',
    acronym: 'BHS',
    mascot: 'Yellowjackets',
    city: 'Berkeley',
    section: 'ncs',
    league: 'mcal',
    division: 'marin-county',
    dataCoverage: 'full',
    colors: ['CC0022', 'C8880A'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/berkeley/berkeley-yellowjackets/field-hockey/',
    aliases: [
      'Berkeley', 'BERKELEY', 'Berkeley High', 'Berkeley High School', 'Berkeley Yellowjackets',
    ],
    sbliveTeamId: '458485',
    sbliveSlug: '458485-berkeley-yellowjackets',
  },
  {
    id: '527c7df0-94c7-4aa2-991c-ef86f4235d4e',
    slug: 'lick-wilmerding',
    name: 'Lick-Wilmerding',
    shortName: 'Lick-Wilmerding',
    abbr: 'LW',
    acronym: 'LWHS',
    mascot: 'Tigers',
    city: 'San Francisco',
    section: 'ncs',
    league: 'mcal',
    division: 'marin-county',
    dataCoverage: 'full',
    colors: ['222222', 'C8880A'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/san-francisco/lick-wilmerding-tigers/field-hockey/',
    aliases: [
      'Lick-Wilmerding', 'LICK-WILMERDING', 'Lick Wilmerding', 'Lick',
      'Lick-Wilmerding High School', 'Lick-Wilmerding Tigers', 'Lick-Wilmerding (San Francisco)',
    ],
    sbliveTeamId: '487098',
    sbliveSlug: '487098-lickwilmerding-tigers',
    sbliveSchoolId: '263',
  },
  {
    id: '7ad2b4f5-955e-4a92-ac1f-a1acced4df4b',
    slug: 'university-sf',
    name: 'San Francisco University',
    shortName: 'SF University',
    abbr: 'UN',
    acronym: 'UHS',
    mascot: 'Red Devils',
    city: 'San Francisco',
    section: 'ncs',
    league: 'mcal',
    division: 'marin-county',
    dataCoverage: 'full',
    colors: ['CC0022', 'FFFFFF'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/san-francisco/university-red-devils/field-hockey/',
    aliases: [
      'University (San Francisco)', 'San Francisco University High School', 'SF University',
      'University High School (San Francisco)', 'University Red Devils',
    ],
    sbliveTeamId: '456869',
    sbliveSlug: '456869-university-red-devils',
    sbliveSchoolId: '259',
  },
  {
    id: '69e24861-fa93-42a2-acb5-be60e01ee555',
    slug: 'marin-catholic',
    name: 'Marin Catholic',
    shortName: 'Marin Catholic',
    abbr: 'MC',
    acronym: 'MCHS',
    mascot: 'Wildcats',
    city: 'Kentfield',
    section: 'ncs',
    league: 'mcal',
    division: 'marin-county',
    dataCoverage: 'full',
    colors: ['022C66', 'FFFFFF'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/kentfield/marin-catholic-wildcats/field-hockey/',
    aliases: [
      'Marin Catholic', 'MARIN CATHOLIC', 'Marin Catholic High School', 'Marin Catholic Wildcats',
      'Marin Catholic (Kentfield)',
    ],
    sbliveTeamId: '456834',
    sbliveSlug: '456834-marin-catholic-wildcats',
    sbliveSchoolId: '163',
  },
  {
    id: 'd15d09d0-f8a6-463e-86d4-d998dbee7751',
    slug: 'convent-sacred-heart',
    name: 'Convent of the Sacred Heart',
    shortName: 'Convent',
    abbr: 'CS',
    acronym: 'CSHHS',
    mascot: 'Cubs',
    city: 'San Francisco',
    section: 'ncs',
    league: 'mcal',
    division: 'marin-county',
    dataCoverage: 'full',
    colors: ['CC0022', 'FFFFFF'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/san-francisco/convent-of-the-sacred-heart-cubs/field-hockey/',
    aliases: [
      'Convent of the Sacred Heart', 'CONVENT', 'Convent', 'Convent & Stuart Hall',
      'Convent and Stuart Hall', 'Convent Sacred Heart', 'Convent of the Sacred Heart High School',
      'Convent of the Sacred Heart Cubs', 'Convent of the Sacred Heart (San Francisco)', 'CSH',
      'CVS',
    ],
    sbliveTeamId: '512325',
    sbliveSlug: '512325-convent-stuart-hall-knights',
    sbliveSchoolId: '6922',
  },
  {
    id: '9f489fa8-a23a-4924-a2a0-5c5cff3c0fdc',
    slug: 'marin-academy',
    name: 'Marin Academy',
    shortName: 'Marin Academy',
    abbr: 'MA',
    acronym: 'MA',
    mascot: 'Wildcats',
    city: 'San Rafael',
    section: 'ncs',
    league: 'mcal',
    division: 'marin-county',
    dataCoverage: 'full',
    colors: ['222222', 'CC0022'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/san-rafael/marin-academy-wildcats/field-hockey/',
    aliases: [
      'Marin Academy', 'MARIN ACADEMY', 'Marin Academy Wildcats', 'Marin Academy (San Rafael)',
    ],
  },
];
