/**
 * The 7 PCAL seeds, transcribed from tests/fixtures/seeds/registry-seed.json (verified 2026-10-02;
 * checked field by field by tests/registry-seeds.test.ts). PCAL plays one division. York (grid slot
 * CAT/YOR) is JV only and is not a member. The PDF grid codes (CAR, GRE, HOL, MON, SAL, CAT, SCAT,
 * CAT/YOR, STE) live in LEAGUES pcal.officialCodes, never in aliases.
 */

import type { Seed } from './seed';

export const PCAL_SEEDS: readonly Seed[] = [
  // ----- PCAL (7) -----
  {
    id: '91994f1e-57af-4fda-9fe0-45c923078af6',
    slug: 'carmel',
    name: 'Carmel',
    shortName: 'Carmel',
    abbr: 'CA',
    acronym: 'CHS',
    mascot: 'Padres',
    city: 'Carmel',
    section: 'ccs',
    league: 'pcal',
    division: 'pcal',
    dataCoverage: 'full',
    colors: ['CC0022', '454444'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/carmel/carmel-padres/field-hockey/',
    aliases: [
      'Carmel', 'CARMEL', 'Carmel Padres', 'Carmel High School',
    ],
    sbliveTeamId: '458529',
    sbliveSlug: '458529-carmel-padres',
    sbliveSchoolId: '10223',
  },
  {
    id: '0bb5dbd8-6792-415b-8118-196ee0132b56',
    slug: 'greenfield',
    name: 'Greenfield',
    shortName: 'Greenfield',
    abbr: 'GR',
    acronym: 'GHS',
    mascot: 'Bruins',
    city: 'Greenfield',
    section: 'ccs',
    league: 'pcal',
    division: 'pcal',
    dataCoverage: 'full',
    colors: ['00824B', '222222'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/greenfield/greenfield-bruins/field-hockey/',
    aliases: [
      'Greenfield', 'GREENFIELD', 'Greenfield Bruins', 'Greenfield High School',
    ],
    sbliveTeamId: '458776',
    sbliveSlug: '458776-greenfield-bruins',
    sbliveSchoolId: '11486',
  },
  {
    id: '3f8f38fb-88f9-44ee-9af1-c1203fce437b',
    slug: 'hollister',
    name: 'Hollister',
    shortName: 'Hollister',
    abbr: 'HO',
    acronym: 'HHS',
    mascot: 'Haybalers',
    city: 'Hollister',
    section: 'ccs',
    league: 'pcal',
    division: 'pcal',
    dataCoverage: 'full',
    colors: ['CC0022', 'FFFFFF'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/hollister/hollister-haybalers/field-hockey/',
    aliases: [
      'Hollister', 'HOLLISTER', 'Hollister Haybalers', 'San Benito', 'San Benito High School',
      'San Benito Haybalers', 'Hollister (San Benito)',
    ],
    sbliveTeamId: '459010',
    sbliveSlug: '459010-hollister-haybalers',
    sbliveSchoolId: '12876',
  },
  {
    id: '1ddbdf6d-84fd-4dfa-942f-f833193e2626',
    slug: 'monterey',
    name: 'Monterey',
    shortName: 'Monterey',
    abbr: 'MO',
    acronym: 'MHS',
    mascot: 'Toreadors',
    city: 'Monterey',
    section: 'ccs',
    league: 'pcal',
    division: 'pcal',
    dataCoverage: 'full',
    colors: ['00824B', 'C8880A'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/monterey/monterey-toreadors/field-hockey/',
    aliases: [
      'Monterey', 'MONTEREY', 'Monterey Toreadors', 'Monterey Toreadores', 'Monterey High School',
    ],
    sbliveTeamId: '458839',
    sbliveSlug: '458839-monterey-toreadores',
  },
  {
    id: '1f152b3b-38dc-4d34-b260-9663dc3006a4',
    slug: 'salinas',
    name: 'Salinas',
    shortName: 'Salinas',
    abbr: 'SA',
    acronym: 'SHS',
    mascot: 'Cowboys',
    city: 'Salinas',
    section: 'ccs',
    league: 'pcal',
    division: 'pcal',
    dataCoverage: 'full',
    colors: ['754ACC', 'FFC005'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/salinas/salinas-cowboys/field-hockey/',
    aliases: [
      'Salinas', 'SALINAS', 'Salinas Cowboys', 'Salinas High School',
    ],
    sbliveTeamId: '459009',
    sbliveSlug: '459009-salinas-cowboys',
    sbliveSchoolId: '12870',
  },
  {
    id: 'c3f83b47-6bab-4e25-ba49-9c3ffda74be8',
    slug: 'santa-catalina',
    name: 'Santa Catalina',
    shortName: 'Santa Catalina',
    abbr: 'CT',
    acronym: 'SCHS',
    mascot: 'Cougars',
    city: 'Monterey',
    section: 'ccs',
    league: 'pcal',
    division: 'pcal',
    dataCoverage: 'full',
    colors: ['034CB2', 'C8880A'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/monterey/santa-catalina-cougars/field-hockey/',
    aliases: [
      'Santa Catalina', 'SANTA CATALINA', 'Santa Catalina Cougars', 'Santa Catalina School',
      'Santa Catalina (Monterey)',
    ],
    sbliveTeamId: '458109',
    sbliveSlug: '458109-santa-catalina-cougars',
  },
  {
    id: 'e9a4a782-76c5-4b15-8dd6-f03b87464aa4',
    slug: 'stevenson',
    name: 'Stevenson',
    shortName: 'Stevenson',
    abbr: 'ST',
    acronym: 'SHS',
    mascot: 'Pirates',
    city: 'Pebble Beach',
    section: 'ccs',
    league: 'pcal',
    division: 'pcal',
    dataCoverage: 'full',
    colors: ['005B34', 'FFFFFF'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/pebble-beach/stevenson-pirates/field-hockey/',
    aliases: [
      'Stevenson', 'STEVENSON', 'Stevenson Pirates', 'Stevenson School', 'Robert Louis Stevenson',
      'Robert Louis Stevenson School', 'Stevenson (Pebble Beach)',
    ],
    sbliveTeamId: '456854',
    sbliveSlug: '456854-stevenson-pirates',
  },
];
