/**
 * The 15 SCVAL seeds, moved verbatim from lib/teams.ts (plus `section`, `league` and the si.com
 * school ids observed on logo URLs). The 15 slugs, abbrs, ids, names and divisions are frozen
 * (tests/teams.test.ts).
 *
 * Division membership comes exclusively from the two official SCVAL PDFs:
 *   De Anza  : https://scval.com/fallSports/26-27%20SCVAL%20FH%20DA%20Final.pdf
 *   El Camino: https://scval.com/fallSports/26-27%20SCVAL%20FH%20EC%20Final.pdf
 *
 * The De Anza grid still lists Wilcox, but Wilcox is not fielding a team this season, so it is
 * not a member here: see LEAGUES scval.withdrawnNames in lib/leagues.ts.
 *
 * Aliases cover: MaxPreps `schoolName`, the SCVAL PDF grid UPPERCASE forms, the SCVAL prose /
 * standings PDF forms, SBLive / si.com names, and the VNN ICS "X High School" forms.
 */

import type { Seed } from './seed';

export const SCVAL_SEEDS: readonly Seed[] = [
  // ----- De Anza (7; Wilcox is on the official grid but not fielding a team) -----
  {
    id: '1dc4836b-4daf-4573-b525-27b474bd5366',
    slug: 'st-ignatius',
    name: 'St. Ignatius',
    shortName: 'St. Ignatius',
    abbr: 'SI',
    acronym: 'SICP',
    mascot: 'Wildcats',
    city: 'San Francisco',
    section: 'ccs',
    league: 'scval',
    division: 'de-anza',
    dataCoverage: 'full',
    colors: ['CC0022', '034CB2'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/san-francisco/st-ignatius-college-preparatory-wildcats/field-hockey/',
    aliases: [
      'St. Ignatius College Preparatory', 'ST. IGNATIUS', 'Saint Ignatius', 'St. Ignatius',
      'St Ignatius', 'SICP', 'St. Ignatius College Prep', 'St. Ignatius Wildcats',
      'St. Ignatius College Preparatory High School',
    ],
    sbliveTeamId: '456831',
    sbliveSlug: '456831-st-ignatius-wildcats',
  },
  {
    id: 'de6d3780-e8f6-4a2a-93f2-b5d89499f9b0',
    slug: 'saint-francis',
    name: 'Saint Francis',
    shortName: 'Saint Francis',
    abbr: 'SF',
    acronym: 'SFHS',
    mascot: 'Lancers',
    city: 'Mountain View',
    section: 'ccs',
    league: 'scval',
    division: 'de-anza',
    dataCoverage: 'full',
    colors: ['503604', 'FFFFFF'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/mountain-view/saint-francis-lancers/field-hockey/',
    aliases: [
      'Saint Francis', 'ST. FRANCIS', 'St. Francis', 'St Francis', 'Saint Francis Lancers',
      'Saint Francis High School', 'Saint Francis (Mountain View)',
    ],
    sbliveTeamId: '457982',
    sbliveSlug: '457982-saint-francis-lancers',
  },
  {
    id: '0279f2de-d5ce-484d-b210-2286ded42058',
    slug: 'los-altos',
    name: 'Los Altos',
    shortName: 'Los Altos',
    abbr: 'LA',
    acronym: 'LAHS',
    mascot: 'Eagles',
    city: 'Los Altos',
    section: 'ccs',
    league: 'scval',
    division: 'de-anza',
    dataCoverage: 'full',
    colors: ['034CB2', '454444'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/los-altos/los-altos-eagles/field-hockey/',
    aliases: ['Los Altos', 'LOS ALTOS', 'Los Altos Eagles', 'Los Altos High School'],
    sbliveTeamId: '458850',
    sbliveSlug: '458850-los-altos-eagles',
    sbliveSchoolId: '12174',
  },
  {
    id: '8a8c04d2-5606-44cf-9993-34db55474240',
    slug: 'valley-christian',
    name: 'Valley Christian',
    shortName: 'Valley Chr.',
    abbr: 'VC',
    acronym: 'VCHS',
    mascot: 'Warriors',
    city: 'San Jose',
    section: 'ccs',
    league: 'scval',
    division: 'de-anza',
    dataCoverage: 'full',
    colors: ['022C66', '046DFF'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/san-jose/valley-christian-warriors/field-hockey/',
    aliases: [
      'Valley Christian', 'VALLEY CHRISTIAN', 'Valley Christian Warriors',
      'Valley Christian High School', 'Valley Christian (San Jose)',
    ],
    sbliveTeamId: '480709',
    sbliveSlug: '480709-valley-christian-warriors',
    sbliveSchoolId: '319',
  },
  {
    id: 'a97c219c-2fbe-4fa4-9a0c-cc18502a8d24',
    slug: 'fremont',
    name: 'Fremont',
    shortName: 'Fremont',
    abbr: 'FR',
    acronym: 'FHS',
    mascot: 'Firebirds',
    city: 'Sunnyvale',
    section: 'ccs',
    league: 'scval',
    division: 'de-anza',
    dataCoverage: 'full',
    colors: ['CC0022', 'FFFFFF'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/sunnyvale/fremont-firebirds/field-hockey/',
    aliases: [
      'Fremont', 'FREMONT', 'Fremont Firebirds', 'Fremont High School', 'Fremont (Sunnyvale)',
    ],
    sbliveTeamId: '496836',
    sbliveSlug: '496836-fremont-firebirds',
    sbliveSchoolId: '11003',
  },
  {
    id: '97ffffbe-54ba-4c25-86bb-41332627f64e',
    slug: 'cupertino',
    name: 'Cupertino',
    shortName: 'Cupertino',
    abbr: 'CU',
    acronym: 'CHS',
    mascot: 'Pioneers',
    city: 'Cupertino',
    section: 'ccs',
    league: 'scval',
    division: 'de-anza',
    dataCoverage: 'full',
    colors: ['CC0022', '454444'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/cupertino/cupertino-pioneers/field-hockey/',
    aliases: ['Cupertino', 'CUPERTINO', 'Cupertino Pioneers', 'Cupertino High School'],
    sbliveTeamId: '458665',
    sbliveSlug: '458665-cupertino-pioneers',
    sbliveSchoolId: '11002',
  },
  {
    id: '738a2432-7acb-4ad6-b041-115ec0f331c2',
    slug: 'homestead',
    name: 'Homestead',
    shortName: 'Homestead',
    abbr: 'HM',
    acronym: 'HHS',
    mascot: 'Mustangs',
    city: 'Cupertino',
    section: 'ccs',
    league: 'scval',
    division: 'de-anza',
    dataCoverage: 'full',
    colors: ['00824B', 'FFFFFF'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/cupertino/homestead-mustangs/field-hockey/',
    aliases: ['Homestead', 'HOMESTEAD', 'Homestead Mustangs', 'Homestead High School'],
    sbliveTeamId: '458667',
    sbliveSlug: '458667-homestead-mustangs',
    sbliveSchoolId: '11004',
  },

  // ----- El Camino (official 8; MaxPreps 8) -----
  {
    id: '0f63870a-34f3-4d5b-9dbf-653c8410f969',
    slug: 'mitty',
    name: 'Archbishop Mitty',
    shortName: 'Mitty',
    abbr: 'MI',
    acronym: 'AMHS',
    mascot: 'Monarchs',
    city: 'San Jose',
    section: 'ccs',
    league: 'scval',
    division: 'el-camino',
    dataCoverage: 'full',
    colors: ['222222', 'C8880A'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/san-jose/archbishop-mitty-monarchs/field-hockey/',
    aliases: [
      'Archbishop Mitty', 'MITTY', 'Mitty', 'Archbishop Mitty Monarchs',
      'Archbishop Mitty High School', 'Mitty High School',
    ],
    sbliveTeamId: '464806',
    sbliveSlug: '464806-archbishop-mitty-monarchs',
  },
  {
    id: 'bdb0b593-ef7f-4c69-8c2a-e0a48c934ca7',
    slug: 'los-gatos',
    name: 'Los Gatos',
    shortName: 'Los Gatos',
    abbr: 'LG',
    acronym: 'LGHS',
    mascot: 'Wildcats',
    city: 'Los Gatos',
    section: 'ccs',
    league: 'scval',
    division: 'el-camino',
    dataCoverage: 'full',
    colors: ['D5350B', '222222'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/los-gatos/los-gatos-wildcats/field-hockey/',
    aliases: ['Los Gatos', 'LOS GATOS', 'Los Gatos Wildcats', 'Los Gatos High School'],
    sbliveTeamId: '458802',
    sbliveSlug: '458802-los-gatos-wildcats',
    vnnSiteId: '2634860',
  },
  {
    id: 'a38a628c-c65f-487f-a65e-7264b6804ce0',
    slug: 'palo-alto',
    name: 'Palo Alto',
    shortName: 'Palo Alto',
    abbr: 'PA',
    acronym: 'PAHS',
    mascot: 'Vikings',
    city: 'Palo Alto',
    section: 'ccs',
    league: 'scval',
    division: 'el-camino',
    dataCoverage: 'full',
    colors: ['005B34', 'FFFFFF'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/palo-alto/palo-alto-vikings/field-hockey/',
    aliases: [
      'Palo Alto', 'PALO ALTO', 'Paly', 'Palo Alto Vikings', 'Palo Alto High School',
    ],
    sbliveTeamId: '480707',
    sbliveSlug: '480707-palo-alto-vikings',
    vnnSiteId: '2635290',
  },
  {
    id: 'e1db3a4f-3bcf-4281-a574-d313212296a1',
    slug: 'presentation',
    name: 'Presentation',
    shortName: 'Presentation',
    abbr: 'PR',
    acronym: 'PHS',
    mascot: 'Panthers',
    city: 'San Jose',
    section: 'ccs',
    league: 'scval',
    division: 'el-camino',
    dataCoverage: 'full',
    colors: ['034CB2', 'C8880A'],
    colorSource: 'maxpreps-standings',
    // NB: the HTML schedule page under this path serves LOS GATOS data (SPEC §2.1, verdict 30).
    // We only ever read this team through the API, keyed on the GUID.
    maxprepsPath: '/ca/san-jose/presentation-panthers/field-hockey/',
    aliases: [
      'Presentation', 'PRESENTATION', 'Presentation Panthers', 'Presentation High School',
      // The 2025-26 all-league PDF writes "Presentation HS" in two places.
      'Presentation HS',
    ],
    sbliveTeamId: '457986',
    sbliveSlug: '457986-presentation-panthers',
  },
  {
    id: '17fad4fb-c82b-4b5a-8a31-3ce13c0ede13',
    slug: 'santa-clara',
    name: 'Santa Clara',
    shortName: 'Santa Clara',
    abbr: 'SC',
    acronym: 'SCHS',
    mascot: 'Bruins',
    city: 'Santa Clara',
    section: 'ccs',
    league: 'scval',
    division: 'el-camino',
    dataCoverage: 'full',
    colors: ['034CB2', 'FFC005'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/santa-clara/santa-clara-bruins/field-hockey/',
    aliases: [
      'Santa Clara', 'SANTA CLARA', 'Santa Clara Bruins', 'Santa Clara High School',
    ],
    sbliveTeamId: '496839',
    sbliveSlug: '496839-santa-clara-bruins',
    sbliveSchoolId: '13089',
  },
  {
    id: '12a470ab-e17d-4e5a-b74b-055d1f46d46b',
    slug: 'saratoga',
    name: 'Saratoga',
    shortName: 'Saratoga',
    // 'SG', not 'SA' or 'SC': the one abbr collision that needed resolving (DESIGN §12.9).
    abbr: 'SG',
    acronym: 'SHS',
    mascot: 'Falcons',
    city: 'Saratoga',
    section: 'ccs',
    league: 'scval',
    division: 'el-camino',
    dataCoverage: 'full',
    colors: ['CC0022', 'FFFFFF'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/saratoga/saratoga-falcons/field-hockey/',
    aliases: ['Saratoga', 'SARATOGA', 'Saratoga Falcons', 'Saratoga High School'],
    sbliveTeamId: '458805',
    sbliveSlug: '458805-saratoga-falcons',
  },
  {
    id: 'd7c7f7a1-06be-44fb-a4a2-64599519aa4c',
    slug: 'lynbrook',
    name: 'Lynbrook',
    shortName: 'Lynbrook',
    abbr: 'LY',
    acronym: 'LHS',
    mascot: 'Vikings',
    city: 'San Jose',
    section: 'ccs',
    league: 'scval',
    division: 'el-camino',
    dataCoverage: 'full',
    colors: ['022C66', 'FFFFFF'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/san-jose/lynbrook-vikings/field-hockey/',
    aliases: ['Lynbrook', 'LYNBROOK', 'Lynbrook Vikings', 'Lynbrook High School'],
    sbliveTeamId: '458669',
    sbliveSlug: '458669-lynbrook-vikings',
  },
  {
    id: '405614ad-a015-4270-b527-18e899c90824',
    slug: 'monta-vista',
    name: 'Monta Vista',
    shortName: 'Monta Vista',
    abbr: 'MV',
    acronym: 'MVHS',
    mascot: 'Matadors',
    city: 'Cupertino',
    section: 'ccs',
    league: 'scval',
    division: 'el-camino',
    dataCoverage: 'full',
    colors: ['754ACC', 'C8880A'],
    colorSource: 'maxpreps-standings',
    maxprepsPath: '/ca/cupertino/monta-vista-matadors/field-hockey/',
    aliases: ['Monta Vista', 'MONTA VISTA', 'Monta Vista Matadors', 'Monta Vista High School'],
    sbliveTeamId: '458672',
    sbliveSlug: '458672-monta-vista-matadors',
  },
];
